tap "homebrew/bundle"
tap "homebrew/core"
tap "bats-core/bats-core"
tap "caarlos0/tap"

brew "bash"
brew "bash-completion@2"
brew "bats-core"
brew "parallel"
brew "bats-core/bats-core/bats-assert"
brew "bats-core/bats-core/bats-file"
brew "bats-core/bats-core/bats-support"
if RUBY_PLATFORM[/darwin/]
  tap "caarlos0/tap"
  brew "caarlos0/tap/svu"
end
